### ISSUE TITLE
Login and register buttons non-functional

### ISSUE THREAD

**Issue by HarryPeach** [MattDavis00/mattdavis.info#19]
Tested in Chrome and Firefox, when trying to login or register, pressing the button or pressing enter has no effect. 

If the boxes are empty, validation will appear asking for them to be filled; yet if all fields are correctly filled the button does nothing and the form does not progress.

**Comment by MattDavis00** [comment]
Cannot reproduce issue in Chrome or Firefox, try clearing your cache and reattempting? Code recently went through a large refactor so may be an issue with cached files. However, using enter to submit any form current doesn't work due to its implementation, please use the buttons for now. This has been opened as an issue: https://github.com/MattDavis00/mattdavis.info/issues/20#issue-477499128

**Comment by MattDavis00** [comment]
Found to be client-side caching issue.
